PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins"
RESSURECT_DIR="$HOME/.tmux/resurrect"
TMUX_CONF_PATH="$HOME/.config/tmux"
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$PLUGIN_MANAGER_PATH"

set -s default-terminal 'tmux-256color'
set -as terminal-features ",xterm-256color:RGB"

set -g escape-time 0 # 150
set -g repeat-time 500
set -g display-time 1000
set -g status-interval 5
set -g focus-events on
set -g mouse on

setw -g pane-base-index 1
set -g base-index 1
set -g renumber-windows on  
set -g history-limit 50000

setw -g mode-keys vi
# set -g status-keys vi

set -g prefix C-Space
bind C-Space send-prefix
unbind C-b

bind r source-file "$TMUX_CONF_PATH/tmux.conf" \; display-message "Tmux config reloaded!"
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

bind-key C-h select-pane -L
bind-key C-j select-pane -D
bind-key C-k select-pane -U
bind-key C-l select-pane -R
bind '\' split-window -h
bind - split-window -v
bind-key q kill-pane
bind k kill-window
unbind l
unbind '"'
unbind %

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind v copy-mode
bind-key / copy-mode \; send-key ?

bind-key -n C-Left swap-window -t -1\; select-window -t -1
bind-key -n C-Right swap-window -t +1\; select-window -t +1

unbind C-f
bind C-f display-popup -h 15 -y "#{e|/:#{e|*:45,#{client_height}},100}" -B -E "$TMUX_CONF_PATH/session-fzf.sh"

# plugins
# TODO: https://github.com/catppuccin/tmux/issues/409 and https://github.com/catppuccin/tmux/pull/577
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none" 
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_number_color "#{@thm_lavender}"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-dir $RESSURECT_DIR
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
# set -g @resurrect-processes ''

set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

set -g @continuum_on_float "#[fg=#{@thm_blue}]#[bg=#{@thm_blue},fg=#{@thm_crust}]󰆓 #[bg=#{@thm_surface_0},fg=default] on" 
set -g @continuum_off_float "#[fg=#{@thm_peach}]#[bg=#{@thm_peach},fg=#{@thm_crust}]󰆓 #[bg=#{@thm_surface_0},fg=default] off" 
set -g status-left ""
set -g status-right "#{?#{match:[0-9],#{continuum_status}},#{E:@continuum_on_float},#{E:@continuum_off_float}} #{E:@catppuccin_status_session}}" 



set -g @plugin 'tmux-plugins/tpm'
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $PLUGIN_MANAGER_PATH/tpm && $PLUGIN_MANAGER_PATH/tpm/bin/install_plugins'"
run "$PLUGIN_MANAGER_PATH/tpm/tpm"

# fixes
set -g popup-style "bg=default,fg=default"
# see issue 409
set -g window-status-format "#[bg=default,fg=#{@thm_surface_0}]#[bg=default,fg=#{@thm_surface_0}]#[bg=#{@thm_surface_0},fg=#{@thm_fg}]#W#[bg=#{@thm_surface_0},fg=#{@thm_surface_0}]█#[bg=#{@thm_lavender},fg=#{@thm_lavender}]█#[bg=#{@thm_lavender},fg=#{@thm_crust}]#I#[bg=default,fg=#{@thm_lavender}]#[bg=default,fg=#{@thm_lavender}]"
set -g window-status-current-format "#[bg=default,fg=#{@thm_surface_1}]#[bg=default,fg=#{@thm_surface_1}]#[bg=#{@thm_surface_1},fg=#{@thm_fg}]#W#[bg=#{@thm_surface_1},fg=#{@thm_surface_1}]█#[bg=#{@thm_mauve},fg=#{@thm_mauve}]█#[bg=#{@thm_mauve},fg=#{@thm_crust}]#I#[bg=default,fg=#{@thm_mauve}]#[bg=default,fg=#{@thm_mauve}]"
